language: php
matrix:
  include:
    - php: 7.2

sudo: false
before_install:
  - export NEOS_TARGET_VERSION=4.2
  - cd ..
  - git clone https://github.com/neos/neos-base-distribution.git -b ${NEOS_TARGET_VERSION}
  - cd neos-base-distribution
  - composer require --no-update --no-interaction neos/neos-ui
  - composer require --no-update --no-interaction neos/neos-ui-compiled
  - composer require --no-update --no-interaction punktde/archivist:dev-master
install:
  - composer install --no-interaction
  - cd ..
  - rm -rf neos-base-distribution/Packages/Application/PunktDe.Archivist
  - mv archivist neos-base-distribution/Packages/Application/PunktDe.Archivist
  - cd neos-base-distribution
script:
  - bin/phpunit --colors --stop-on-failure -c Build/BuildEssentials/PhpUnit/FunctionalTests.xml Packages/Application/PunktDe.Archivist/Tests/Functional
